### PR TITLE
Use vanilla Leaflet 1.7.1

### LINKED ISSUE #79: Upgrade to most recent version of Leaflet
Hi there,

currently, this repository includes Leaflet 1.3.1 on behalf of the [`src/libs/leaflet.js`](https://github.com/panodata/grafana-map-panel/blob/0.13.0/src/libs/leaflet.js) file. However, it should be better included by adding it as a runtime dependency into `package.json`.

Within #78, we are looking at integrating [Leaflet-Geoman](https://geoman.io/leaflet-geoman) and I believe it will be a good idea to also bump to the most recent version of Leaflet when/before doing that.

With kind regards,
Andreas.

### PR DESCRIPTION
**Pull request by amotl**
Closes #79.

## About
This attempts to remove the Leaflet 1.3.1 included within the repository and replace it by a vanilla Leaflet 1.7.1 pulled in through `package.json`.

### CODE REVIEW

**Comment by amotl** [comment]
Dear @robouden and @matschaffer,

I've compiled this as [grafana-map-panel-0.14.0-pre1.zip](https://github.com/panodata/grafana-map-panel/files/5507455/grafana-map-panel-0.14.0-pre1.zip). Will you be able to test it?

With kind regards,
Andreas.

**Comment by robouden** [comment]
Andreas

I will give it a try.

Regards,
Rob

**Comment by robouden** [comment]
Andreas,

I installed to plugin and it seems to work fine. See
https://grafana.safecast.cc/d/u5-KaDEWk/air-data?orgId=1
What do you want me to test with it?

Regards,
Rob




Regards,
Rob Oudendijk Yuka Hayashi
http://yr-design.biz   http://oudendijk.biz  http://about.me/robouden
tel +81 80-22605966  Skype: robouden  Facebook:robouden
<http://on.fb.me/QeKw2P> linkedin:robouden
<https://www.linkedin.com/in/roboudendijk>

**Comment by amotl** [comment]
Hi Rob,

> I installed to plugin and it seems to work fine.

Thanks!

> What do you want me to test with it?

If the rendering is still working after swapping the Leaflet implementation, I believe it will all be fine then. Thanks for your quick test!

Cheers,
Andreas.

**Comment by robouden** [comment]
Andreas,

Yes, works fine. 

Regards,
rob

**Pull request merged**
