### PR TITLE
added handling for data coming from datasources using dataframes

### PR DESCRIPTION
**Pull request by sarahleon**
I am currently working on the Grafana Sensorthings Datasource and we use the map panel for displaying our data. Due to the recent refactoring of Grafanas datahandling our datasource has stopped working with the map panel. This commit fixes the issue whilst datasources under older versions of Grafana should still work.

### CODE REVIEW

**Comment by amotl** [comment]
Dear Sarah,

thanks for your contribution! Can you add another method in order not to duplicate the essence of the code, i.e. from `const dataValue = ...` to `data.push(dataValue)`?

Thanks already and with kind regards,
Andreas.

**Comment by sarahleon** [comment]
Dear Andreas,

I finally got around to following up on your comment. I have created two new methods: 

- one for creating the data value object: here there was already one method but using the geohash, which was not needed in this case, so I renamed it for the time being. However I think that both methods could easily be merged. If you are OK with this, I could do so.

- and one for calculating the value range: this one also could be reused in other methods and again I offer to do this.

I hope this is helpful.

Kind regards,
Sarah

**Comment by amotl** [comment]
Dear Sarah,

thanks for improving your pull request. This looks way more compact and concise and I will be happy to merge this.

If you see more improvements to streamline the code base, I would appreciate receiving further pull requests separate from this one. In order to be safe nothing breaks, we should think about improving the test coverage as well.

With kind regards,
Andreas.

**Comment by sarahleon** [comment]
Dear Andreas,

you are absolutely right. Best to separate further streamlining of the code into a different pull request in order to keep things nice and tidy. 

What about the test coverage - should we disconnect that from this pull request too or do you want me to expand it before you merge?

Kind regards,
Sarah

**Comment by amotl** [comment]
I've tried to improve coverage in the past around support for table data and timeseries data while adding some more features but I don't exactly know about the current state for `setJsonValues`.

So, feel free to add test coverage for your specific use case if you find the test harness still lacks support for that. I will be happy to keep the PR open, so please take your time, I'm traveling right now anyway.

**Comment by sarahleon** [comment]
OK, great. Then I will look into it and get back to you.

**Comment by sarahleon** [comment]
Hi Andreas,
sorry for the long silence - things have been a bit crazy at my end and I did not have the time to continue working on this.

I have just fixed some conflicts for this fork. Since I fear I will not get around to writing the tests anytime soon, please feel free to just merge this branch, if it is OK with you.

A problem I have noticed since merging the base branch into this fork: the location circle is not updating anymore. The centering on the last hash works, but the circle stays in the same location. But I think this should be a different pull request (If you are not already working on it)

Kind regards,
Sarah

**Comment by sarahleon** [comment]
FYI: I just fixed the problem with the dot not updating, turns out it was a issue on our side...

**Comment by amotl** [comment]
Dear Sarah,

thanks for bringing this up to speed. I've merged your improvements and added some basic tests through 5317a7c7 and 3f77d553.

With kind regards,
Andreas.

**Comment by sarahleon** [comment]
Great, thanks for merging and adding the tests!

**Comment by amotl** [comment]
Dear Sarah,

we finally included your improvements within an official release. It should be part of 0.10.0 and up.

With kind regards,
Andreas.

**Pull request merged**
