### PR TITLE
Use "next" rather than "canary" for toolkit

### PR DESCRIPTION
**Pull request by ryantxu**
All this did was change canary to next (and then run `yarn dev`)

image

### CODE REVIEW

**Comment by amotl** [comment]
> change canary to next

That sounds easy. Thank you for making the corresponding fixes to the code base.

However, I am asking myself now if this will break again as soon as I might need some features from _canary_ or do you know the exact reason why this works with _next_ and not with _canary_?

**Comment by ryantxu** [comment]
"canary" changes with each commit to master

"next" changes with each release, and importantly when there is a beta release.

BUT it is actually the yarn.lock file that was blocking things -- since that fixes things to the exact version at the time you ran the script

**Comment by amotl** [comment]
Thanks for this background information, @ryantxu. While I am still wondering why this exactly broke only the _reporting_ task on CircleCI is still beyond my imagination.

When something was wrong with the `yarn.lock` file, the other tasks coming from Grafana Toolkit should have failed as well, no?

**Comment by amotl** [comment]
> "canary" changes with each commit to master

Ah, got it. So, there's just no way of using canary together with a `yarn.lock` which nails the version, as the reference to canary is always a moving target. I see.

So, when actually wanting to build this "on the edge of canary" - even through CI - then one would have to remove the version pinning for `grafana-toolkit` from `yarn.lock` at all?

**Comment by ryantxu** [comment]
> then one would have to remove the version pinning for grafana-toolkit from yarn.lock at all - right?

Yes -- for canary to work you have to remove stuff from yarn.lock also.

The report issue was fixed immediately before the 6.6 release, but I think your yarn.lock pinned it to an earlier version

**Comment by amotl** [comment]
> The report issue was fixed immediately before the 6.6 release.

Ah, it was even coming from Grafana Toolkit itself? Ok, thanks again for the clarification around all the bits involved.

**Pull request merged**
